version: "3"

services:  
  application:
    container_name: backend-app
    restart: always
    build: .
    ports:
      -  "8080:3000"
    links:
      - mongo
  mongo:
    container_name: stori-db
    image: mongo
    ports:
      -  "27018:27017"